// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEcr6js2OZ5_0nxBWJA-QdVVyHP7-une8',
    appId: '1:147723250558:web:6b0e033703cf1a08d2612f',
    messagingSenderId: '147723250558',
    projectId: 'zirvenew',
    authDomain: 'zirvenew.firebaseapp.com',
    storageBucket: 'zirvenew.firebasestorage.app',
    measurementId: 'G-3PVL3YF4BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXl4g4O8iOs4L7acpSujJtjY1Sal93at4',
    appId: '1:147723250558:android:fd4b84ce56b02053d2612f',
    messagingSenderId: '147723250558',
    projectId: 'zirvenew',
    storageBucket: 'zirvenew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEcr6js2OZ5_0nxBWJA-QdVVyHP7-une8',
    appId: '1:147723250558:ios:8a7f62f706d26d0ad2612f',
    messagingSenderId: '147723250558',
    projectId: 'zirvenew',
    storageBucket: 'zirvenew.firebasestorage.app',
    iosBundleId: 'com.zirvego.kurye',
  );
}

